Error in dir.exists(reference) : invalid filename argument Calls: RunAzimuth ->
RunAzimuth.Seurat -> dir.exists
Traceback:
3: dir.exists(reference)
2: RunAzimuth.Seurat(query_adata, reference = REFERENCE)
1: RunAzimuth(query_adata, reference = REFERENCE)

